# Generated by Django 3.1.4 on 2020-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
