# Generated by Django 3.1.4 on 2020-12-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_car_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200, unique=True)),
                ('slot1', models.IntegerField(default=0)),
                ('slot2', models.IntegerField(default=0)),
                ('slot3', models.IntegerField(default=0)),
                ('slot4', models.IntegerField(default=0)),
                ('slot5', models.IntegerField(default=0)),
                ('slot6', models.IntegerField(default=0)),
                ('slot7', models.IntegerField(default=0)),
                ('slot8', models.IntegerField(default=0)),
                ('slot9', models.IntegerField(default=0)),
                ('slot10', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='allowed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='car',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='car',
            name='level',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='car',
            name='regno',
            field=models.CharField(default='XXXXXXXX', max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='slot',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='in', max_length=3),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='nocolor', max_length=10),
        ),
    ]
