# Generated by Django 3.1.4 on 2020-12-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20201208_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
