# Generated by Django 3.1.4 on 2020-12-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_car_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('slotAllotted', models.CharField(default=0, max_length=3)),
                ('ticketNo', models.CharField(default='XXX', max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='regno',
            field=models.CharField(default='XXXXXXXX', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.car'),
        ),
    ]
