# Generated by Django 3.1.4 on 2020-12-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20201208_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='regno',
            field=models.CharField(default='XXXXXXXX', max_length=15, primary_key=True, serialize=False),
        ),
    ]
