# Generated by Django 3.1.4 on 2020-12-08 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20201208_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='regno',
            field=models.CharField(default=uuid.uuid1, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketNo',
            field=models.CharField(default=uuid.uuid3, max_length=3, primary_key=True, serialize=False),
        ),
    ]
