# Generated by Django 3.1.4 on 2020-12-08 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_auto_20201208_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketNo',
            field=models.CharField(default=uuid.uuid1, max_length=3, primary_key=True, serialize=False),
        ),
    ]
