# Generated by Django 3.1.4 on 2020-12-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_auto_20201209_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deviceId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ticketing.device'),
        ),
    ]
